# Generated by Django 5.2.7 on 2025-11-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_orderitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'آماده پرداخت'), ('processing', 'درحال پردازش سفارش'), ('shipping', 'ارسال به مشتری'), ('delivered', 'تحویل به مشتری')], default='pending', max_length=10),
        ),
    ]
