# Generated by Django 5.2.7 on 2025-11-11 08:25

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_order_date_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
