# Generated by Django 5.2.7 on 2025-11-02 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_size_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
