# Generated by Django 5.2.7 on 2025-11-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='seal_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
